name: flutter_application_1
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  url_launcher: ^6.1.10
  qr_flutter: ^4.0.0
  flutter_svg: ^1.1.0  # Adicione esta linha para suporte a SVGs


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
